### ISSUE TITLE
Any particular reason why this client is REST based rather than BOLT based? How is the performance comparison between the 2 protocols.

### ISSUE THREAD

**Issue by achandak123** [jmcvetta/neoism#107]

**Comment by jmcvetta** [comment]
Because Bolt didn't exist when I wrote it.  And none of the companies that use this driver have ever contributed a single dime towards its development.  So there's zero chance I'm going to anymore unpaid work on it.

That said, if you would find Bolt support useful, and your company is willing to pay California rates for development work - then we can totally discuss adding Bolt support.
