### ISSUE TITLE
Batch support

### ISSUE THREAD

**Issue by jmcvetta** [jmcvetta/neoism#2]
Thinking about how to implement batch operations.  Afaik the REST API allows any standard call to be included in a batch operation.  A not-yet-existing node can be referred to by its batch ID number.  It _looks_ like the batch ID syntax (`{ 2 }` refers to the result of batch item 2) gets replaced in subsequent commands by the `self` URL of the previously created entity.  Not sure how well this will work for all operations.  

For instance, we can probably add a newly created node to an index by supplying the batch ID syntax in the `uri` field of the POST.  But how can we delete that same index later in the batch, since the actual node ID is required to compose the URL for the DELETE request?

Should batch support be added to existing Node and Relationship objects?  That approach means that some methods, when used in a batch, will _always_ return errors.  Maybe it is better to have separate TxNode and TxRelationship objects with a limited subset of methods?

http://www.mail-archive.com/user@lists.neo4j.org/msg14045.html

The py2neo driver lets you do index removes in a batch, but they can only refer to a pre-existing node:  https://github.com/nigelsmall/py2neo/blob/master/src/py2neo/neo4j.py#L390

**Comment by hamin** [comment]
@jmcvetta The current batch support doesn't include support for batch inserts (creating nodes, adding labels, creating relationships). We've been doing this using the ruby client specifically to reduce the number of http requests made to the Neo4J server when running some import heavy tasks that happen quite regularly. The transactional api will still make multiple HTTP requests to the server so its not actually batching them.

Am I missing something here? I'm bringing this up because we're in need of batch insert support for creating node, adding relationships etc. Currently I'm looking to this older neo4j wrapper https://github.com/cihangir/neo4j . Its missing label support but I'm working on adding that t right now. 

Neoism just seems like the most up to date neo4j client in Go. I was wondering if there would be any plans to include batched operations support to neoism? I'd be glad to help out.

**Comment by jmcvetta** [comment]
Hi @hamin - I am open to including batch insert support, if you would like to implement it.  I can see how it would be generally useful.  Happy to chat or give feedback, but I don't currently have time to work on the code myself.
