### ISSUE TITLE
Error building newest version

### ISSUE THREAD

**Issue by troq** [jmcvetta/neoism#82]
I get this error 

`../../jmcvetta/neoism/entity.go:61: not enough arguments in call to e.Db.Session.Delete`

Looks to be because Delete requires `url string, p *url.Values, result, errMsg interface{}` now instead of `url string, result, errMsg interface{}`.

**Comment by charlesmata** [comment]
:+1: thanks @troq

**Comment by jmcvetta** [comment]
The immediate issues here was, just as @troq said, the change in number of arguments expected by Napping's `Delete()` method.  

However in the process of fixing this I discovered another bug in Napping that had been introduced unnoticed in a recent PR merge.  That bug prevented tests from passing even when the aforementioned API issue was corrected.  

This bug should now be fixed in Neoism v1.1.1, the current `master`.

**Comment by troq** [comment]
Thanks @jmcvetta!
